Emacs Project Helper

* Definitions

** Project

From a user standpoint it's a directory that has .ph file in it. Every
other file in the directory belongs to the project. User may think that
the directory is the project itself & .ph file is just the file that
emacs requires to keep track of the project files.

If a user opens some file within the project directory, ph records that
in .ph file. If user kills buffer with that file, ph removes it from the
database.

Child directories (dired buffers) cannot be recorded in .ph file, but
they are automatically marked as project belongings if user opens them,
so when closing the project they will be closed too.

** Project Name

A directory with project files. For example, if /foo/bar contains .ph
file then project name is 'bar'. If / directory contains .ph, then
project name is 'Root'. If there are 2 open projects in 2 directories:
/foo/bar & /bar their names will be 'bar' and 'bar<2>' correspondingly.

Project names are dynamic & are generated automatically in the similar
manner emacs invents buffer names.

** Subproject

It's possible to have one project enclosed into another. Technically
they are completely independent from each other. It's not possible to
have a file that belongs to 2 projects. (Symlinks? FIXME)

* CL Utils

| Name           | Desc                                           |
|----------------+------------------------------------------------|
| ph-project-new | Create a project db. Use with caution, because |
|                | it's not capable in emacs batch mode to handle |
|                | subprojects that are opened in another emacs   |
|                | instance.                                      |
|----------------+------------------------------------------------|
| ph-make-pkg    | Generate ph-pkg.el from meta.json.             |

* Lisp

ph is a global minor mode. For saving/removing data in .ph file we use
find-file-hook & kill-buffer-hook.

** Project

Object that represent project in memory ('ven' is from venture):

: (cl-defstruct ph-ven
:   db
:   version
:   opfl
: )

Its serialised version is a '.ph' file. ph-ven contains its absolute
path (db). opfl is a hash of currently opened project files in
emacs. When user load the project, PH tries to open all files mentioned
in the hash. If user kills a buffer with one of project files, PH
deletes its name form opfl.

db is always a full path to the .ph file. opfl contains only relative
paths to the parent dir (this is done for easily moving the project
directory elsewhere).

** Global List

ph-vl is a list of ph-ven cells and holds currently opened projects in
emacs. It's persistent across toggling ph-mode but vanishes on emacs
exit.

** Project Actions

All user-level commands are in interactive ph-project-* functions.

| Name                                   | Modifies ph-vl | Modifies db |
|----------------------------------------+----------------+-------------|
| ph-project-open                        | x              | x           |
| ph-project-close                       | x              |             |
| ph-project-which                       |                |             |
| ph-project-new                         | x              | x           |
| ph-project-switch-buffer               |                |             |
| ph-project-switch                      |                |             |
| ph-project-switch-buffer-other-project |                |             |

Its prohibited to parse or modify db file or corresponding cell in ph-vl
list. Use only ph-venture-* & ph-vl-* functions for that.

** Project Buffers

On opening a file, ph checks if its (sub) directory has a .ph database
file & if is, it marks the buffer as such that belongs to the
project. The same goes for dired buffers.

A "mark" is just a buffer local variable ph-buffer-pobj that points to
a cell in global ph-vl list.

N.B. To mark buffer, the corresponding project must be already opened.

** Buffer Local Variables

... are permanent-local.

| Name                     | Desc                                      |
|--------------------------+-------------------------------------------|
| ph-buffer-pobj           | A pointer to ph-vl cell.                  |
|                          |                                           |
| ph-buffer-orig-file-name | A relative to project root dir file name. |
|                          | Used by ph-before-save-hook.              |

** Hooks

| Name                       | Modifies ph-vl | Modifies db |
|----------------------------+----------------+-------------|
| ph-find-file-hook          | x              | x           |
| ph-kill-buffer-hook        | x              | x           |
| ph-dired-after-readin-hook | x              |             |
| ph-before-save-hook        | x              | x           |
